services:
  api:
    build: .
    container_name: pubmed_api
    env_file:
      - .env
    ports:
      - "80:8000"
    depends_on:
      - redis
    command: ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "main:app", "-b", "0.0.0.0:8000"]

  redis:
    image: "redis:alpine"
    container_name: pubmed_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
